// <auto-generated />
using System;
using HxCore.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HxCore.Migrate.Migrations
{
    [DbContext(typeof(HxContext))]
    [Migration("20190825083209_AddTable")]
    partial class AddTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("HxCore.Model.UserInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Activate")
                        .HasColumnType("char")
                        .HasMaxLength(1);

                    b.Property<string>("Admin")
                        .HasColumnType("char")
                        .HasMaxLength(1);

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500);

                    b.Property<string>("Delete")
                        .HasColumnType("char")
                        .HasMaxLength(1);

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("LastLoginTime");

                    b.Property<string>("Lock")
                        .HasColumnType("char")
                        .HasMaxLength(1);

                    b.Property<string>("LoginIp")
                        .HasMaxLength(100);

                    b.Property<string>("NickName")
                        .HasMaxLength(100);

                    b.Property<string>("OpenId")
                        .HasMaxLength(80);

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<DateTime>("RegisterTime");

                    b.Property<string>("UseMdEdit")
                        .HasColumnType("char")
                        .HasMaxLength(1);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("UserInfo");

                    b.HasData(
                        new
                        {
                            Id = 1000L,
                            Activate = "Y",
                            Admin = "N",
                            Delete = "N",
                            Email = "stjworkemail@163.com",
                            LastLoginTime = new DateTime(2019, 8, 25, 16, 32, 9, 48, DateTimeKind.Local).AddTicks(3011),
                            Lock = "N",
                            NickName = "超级管理员",
                            PassWord = "F59BD65F7EDAFB087A81D4DCA06C4910",
                            RegisterTime = new DateTime(2019, 8, 25, 16, 32, 9, 36, DateTimeKind.Local).AddTicks(3035),
                            UseMdEdit = "N",
                            UserName = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
